### ISSUE TITLE
This needs .Net 4.6?

### ISSUE THREAD

**Issue by laurentopia** [Mikilo/ng-unity-versioner#1]

**Comment by Mikilo** [comment]
Not necessarily, didn't try

**Comment by laurentopia** [comment]
in dotnet 3.5 I get this
`interpolated strings' cannot be used because it is not part of the C# 4.0 language specification

**Comment by Mikilo** [comment]
Oh crap, I can fix it easily

**Comment by Mikilo** [comment]
What version of Unity are you using?

**Comment by laurentopia** [comment]
2017 LTS at the moment, working my way to 2020.1

**Comment by Mikilo** [comment]
Oh, very strange, because NG Unity Versioner has been developped against 2017 LTS as well.

If you could provide me any log to help me in the task, I would greatly appreciate

**Comment by Mikilo** [comment]
This is how my scan parameters looks like:

![image](https://user-images.githubusercontent.com/3229550/78726666-9087c800-7900-11ea-9bbe-1715ee558bca.png)

Can you try to scan with one single version? To check if the crash is global.

**Comment by laurentopia** [comment]
> Can you try to scan with one single version? To check if the crash is global.

sorry I don't understand

**Comment by laurentopia** [comment]
![image](https://user-images.githubusercontent.com/26075468/78728717-ea7e9280-78ec-11ea-981b-63b8ff6b0f90.png)

![image](https://user-images.githubusercontent.com/26075468/78728724-f36f6400-78ec-11ea-9b74-d4b09a0200f1.png)


2017.4.39f1

**Comment by laurentopia** [comment]
empty project with PUN2 and post processint stack v2

**Comment by Mikilo** [comment]
Take this version. I made it especially for you (Targetting .NET 3.5)

Keep me in touch if you see anything

**Comment by Mikilo** [comment]
This version.

[NG Unity Versioner.zip](https://github.com/Mikilo/ng-unity-versioner/files/4448033/NG.Unity.Versioner.zip)

**Comment by laurentopia** [comment]
thanks! it works :)
![image](https://user-images.githubusercontent.com/26075468/78833063-1f4c2180-79a1-11ea-93c9-dc3d7755d82e.png)

**Comment by Mikilo** [comment]
Oh yeah, good to hear!

Don't forget to put a filter namespace, otherwise it will scan your entire codebase!

Also, I never tested it with complex and big projects. I can't tell how reliable is the algorithm.

Feel free to contact me if you see anything!
