### ISSUE TITLE
namespace filter out

### ISSUE THREAD

**Issue by laurentopia** [Mikilo/ng-unity-versioner#2]
I'd like to show everything but UnityEngine.Rendering which I'm sure gets auto upgraded
Is there a way?

**Comment by Mikilo** [comment]
Hum... Not in the actual state. But I can implement filters with an in/out directive.

**Comment by laurentopia** [comment]
yay! you rock!

**Comment by Mikilo** [comment]
Take this version, it contains your filters.

[NG Unity Versioner.zip](https://github.com/Mikilo/ng-unity-versioner/files/4458301/NG.Unity.Versioner.zip)
