### ISSUE TITLE
option to not show things that unity auto upgrade

### ISSUE THREAD

**Issue by laurentopia** [Mikilo/ng-unity-versioner#3]
a button to exclude from the list all the things that unity auto upgrade

For example 
![image](https://user-images.githubusercontent.com/26075468/78833263-6df9bb80-79a1-11ea-9a86-b0b55291a519.png)
I'm pretty sure those are handled automatically. Or maybe that's wishful thinking, I'd like to know that.

**Comment by Mikilo** [comment]
The tool warns you about items marked with [Obsolete].

I don't make any assumption and show you everything.

Because I can't tell what is the [Obsolete] about, I can't not easily discard them.
That is particularly subjective.
